#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "2.0.0"
COMMIT = "bd1a30db21ccdce0b38d15aaecab94c82f94efd9"
MAJOR = 2
MINOR = 0
PATCH = 0
