#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "1.1.0"
COMMIT = "5d5a5cbd12ef49909d78c2247a2f988efb9c4894"
MAJOR = 1
MINOR = 1
PATCH = 0
