#
# Copyright (C) 2020 Arm Mbed. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
"""The version number is based on semantic versioning.

References
- https://semver.org/
- https://www.python.org/dev/peps/pep-0440/

This file is autogenerated, do not modify by hand.
"""
__version__ = "2.0.1"
COMMIT = "751fcb24d83ea706212f91cb636ca31f9b43e4de"
MAJOR = 2
MINOR = 0
PATCH = 1
