steps:
  - bash: |
      echo "##vso[task.setvariable variable=temp_docs_path]`cd-get-config --key DOCUMENTATION_PRODUCTION_OUTPUT_PATH`"
    displayName: 'Set variable for temporary docs dir'
  - script: |
      cd-generate-docs --output_dir $(temp_docs_path)
    displayName: 'Generate documentation'
  - script: |
      cd-license-files
    displayName: 'Add copyright/licence notice.'